Handle datetime format while doing json dumps
usc-isi-i2/effect-workflows pull request #1
Opened 2016-09-22 22:26 UTC by darkshadows123

2016-09-23 16:39 UTC, dkapoor requested changes
Does this even work? Your class is named `MyrEncoder` and when you are using it, you are calling it by the name `MyEncoder`. Can you fix this and make sure it works and change the name to be something that reflects its functionality.

Thanks.

2016-09-27 17:15 UTC, darkshadows123 commented
@dkapoor  Changes has been done. Please review

2016-09-27 17:16 UTC, darkshadows123 commented
My local changes still shows Myencoder instead of Myrencoder. I think I did something while forking out.

2016-09-27 17:17 UTC, dkapoor approved these changes

2016-09-27 17:17 UTC, merged